name: Run Crypto News Agent

on:
  schedule:
    - cron: '*/5 * * * *'  # ⏱️ تشغيل كل 5 دقائق
  workflow_dispatch:        # ⏱️ إمكانية التشغيل اليدوي أيضًا

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Save Google credentials from secret
        run: |
          echo "$GOOGLE_CREDENTIALS" > ${{ github.workspace }}/google_credentials.json

      - name: Run news agent script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_FILE: ${{ github.workspace }}/google_credentials.json
        run: |
          python news_agent.py
